NhuDangCenter/Models/HRM_USER.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhuDangCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HRM_USER()
        {
            this.HRM_USERROLES = new HashSet<HRM_USERROLES>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRM_USERROLES> HRM_USERROLES { get; set; }
    }
}

NhuDangCenter/Controllers/HRM_USERController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NhuDangCenter.Models;

namespace NhuDangCenter.Controllers
{
    public class HRM_USERController : Controller
    {
        private NhuDangCenterEntities db = new NhuDangCenterEntities();

        public JsonResult IsExists(string UserName)
        {
            //check if any of the UserName matches the UserName specified in the Parameter using the ANY extension method.  
            return Json(!db.HRM_USER.Any(x => x.UserName == UserName), JsonRequestBehavior.AllowGet);
        }

        // GET: HRM_USER
        public ActionResult Index()
        {
            return View(db.HRM_USER.Include(u=>u.HRM_USERROLES).ToList());
        }

        // GET: HRM_USER/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HRM_USER hRM_USER = db.HRM_USER.Find(id);
            if (hRM_USER == null)
            {
                return HttpNotFound();
            }
            return View(hRM_USER);
        }

        // GET: HRM_USER/Create
        public ActionResult Create()
        {
            return PartialView();
        }

        // POST: HRM_USER/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserID,UserName,Password,FullName")] HRM_USER hRM_USER)
        {
            if (ModelState.IsValid)
            {
                hRM_USER.Password = ThanhUtilities.GetMd5Hash(hRM_USER.Password);
                db.HRM_USER.Add(hRM_USER);
                db.SaveChanges();
                return Json(new { success=true}, JsonRequestBehavior.AllowGet);
            }

            return PartialView(hRM_USER);
        }

        // GET: HRM_USER/Edit/5
        public ActionResult EditUserRoles(int id)
        {
            var us = db.HRM_USER.Find(id);
            if (us == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = us.UserID;
            ViewBag.TenTaiKhoan = us.FullName;
            var roles = (from r in db.HRM_ROLE
                                where !db.HRM_USERROLES.Any(f => f.UserID == id && f.RoleID == r.RoleID)
                                select r);
            return PartialView(roles.ToList());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditUserRoles(int UserID, int[] chkRole)
        {
            if (ModelState.IsValid)
            {
                foreach (int id in chkRole)
                {
                    HRM_USERROLES ur = new HRM_USERROLES();
                    ur.UserID = UserID;
                    ur.RoleID = id;
                    db.HRM_USERROLES.Add(ur);
                }
                db.SaveChanges();
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }

            var us = db.HRM_USER.Find(UserID);
            if (us == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = us.UserID;
            ViewBag.TenTaiKhoan = us.FullName;
            var roles = (from r in db.HRM_ROLE
                         where !db.HRM_USERROLES.Any(f => f.UserID == UserID && f.RoleID == r.RoleID)
                         select r);
            return PartialView(roles.ToList());

        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HRM_USER hRM_USER = db.HRM_USER.Find(id);
            if (hRM_USER == null)
            {
                return HttpNotFound();
            }
            return View(hRM_USER);
        }

        // POST: HRM_USER/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserID,UserName,Password,FullName")] HRM_USER hRM_USER)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hRM_USER).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hRM_USER);
        }
        public ActionResult ChangePassword(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HRM_USER hRM_USER = db.HRM_USER.Find(id);
            if (hRM_USER == null)
            {
                return HttpNotFound();
            }
            return PartialView(hRM_USER);
        }

        // POST: HRM_USER/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangePassword(string Password, int UserID)
        {
            HRM_USER obj = db.HRM_USER.Find(UserID);
            if (ModelState.IsValid)
            {
                obj.Password = ThanhUtilities.GetMd5Hash(Password);
                db.Entry(obj).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success=true}, JsonRequestBehavior.AllowGet);
            }
            return PartialView(obj);
        }
        // GET: HRM_USER/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HRM_USER hRM_USER = db.HRM_USER.Find(id);
            if (hRM_USER == null)
            {
                return HttpNotFound();
            }
            return PartialView(hRM_USER);
        }

        // POST: HRM_USER/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HRM_USER hRM_USER = db.HRM_USER.Find(id);
            db.HRM_USER.Remove(hRM_USER);
            db.SaveChanges();
            return Json(new { success=true},JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NhuDangCenter/Views/HRM_USER/ChangePassword.cshtml
@model NhuDangCenter.Models.HRM_USER
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Đổi password cho người dùng: @Model.FullName</h4>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="modal-body">
        <div class="form-horizontal">
           @Html.ValidationSummary(true, "", new { @class = "text-danger" })        
           @Html.HiddenFor(model => model.UserID)
            <div class="form-group">
                <label class="control-label col-md-4">Password mới</label>
                <div class="col-md-8">
                    <input class="form-control" id="password" name="Password" type="password" />
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-4">Xác nhận password</label>
                <div class="col-md-8">
                    <input class="form-control" id="confirm_password" type="password"/>
                    <span id="messageConfirmPass"></span>
                </div>
            </div>        
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn btn-default" data-dismiss="modal" style="margin-bottom:0px;">
            <i class="fa fa-ban"></i> Hủy
        </button>
        <button class="btn btn-success" type="submit">
            <i class="fa fa-save"></i> Lưu thông tin
        </button>
    </div>

}

NhuDangCenter/Views/HRM_USER/Create.cshtml
@model NhuDangCenter.Models.HRM_USER
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Thêm người dùng</h4>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="modal-body">
        <div class="form-horizontal">
           @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @type ="password", @id="password" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-4">Xác nhận password</label>
            <div class="col-md-8">
                <input class="form-control" id="confirm_password" type="password"/>
                <span id="messageConfirmPass"></span>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn btn-default" data-dismiss="modal" style="margin-bottom:0px;">
            <i class="fa fa-ban"></i> Hủy
        </button>
        <button class="btn btn-success" type="submit">
            <i class="fa fa-save"></i> Lưu thông tin
        </button>
    </div>

}

NhuDangCenter/Views/HRM_USER/Delete.cshtml
@model NhuDangCenter.Models.HRM_USER

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Bạn có chắc muốn tài khoản này?</h4>
</div>
<div class="modal-body">
    <table class="table no-border table-striped table-hover">
        <tr>
            <th>@Html.DisplayNameFor(model => model.UserName):</th>
            <td>@Html.DisplayFor(model => model.UserName)</td>
        </tr>
        <tr>
            <th>@Html.DisplayNameFor(model => model.FullName):</th>
            <td>@Html.DisplayFor(model => model.FullName)</td>
        </tr>        
    </table>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="modal-footer">
        <button class="btn btn-default" data-dismiss="modal" style="margin-bottom:0px;">
            <i class="fa fa-ban"></i> Hủy
        </button>
        <button class="btn btn-danger" type="submit">
            <i class="fa fa-trash"></i>Xóa
        </button>
    </div>
}

NhuDangCenter/Views/HRM_USER/Details.cshtml
@model NhuDangCenter.Models.HRM_USER

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>HRM_USER</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.UserID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NhuDangCenter/Views/HRM_USER/Edit.cshtml
@model NhuDangCenter.Models.HRM_USER

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>HRM_USER</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserID)

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

NhuDangCenter/Views/HRM_USER/EditUserRoles.cshtml
@model IEnumerable<NhuDangCenter.Models.HRM_ROLE>

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Thêm quyền cho tài khoản: @ViewBag.TenTaiKhoan</h4>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="modal-body">
        <em>Chọn những quyền để thêm vào tài khoản: <strong>@ViewBag.TenTaiKhoan</strong>. Sau đó bấm nút thêm.</em>
        <div class="form-horizontal">
            @foreach (var item in Model)
            {
                <div class="checkbox">
                    <label><input type="checkbox" value="@item.RoleID" name="chkRole">@item.RoleFullName</label>
                </div>
            }
            <input type="hidden" value="@ViewBag.UserID" name="UserID" />
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn btn-default" data-dismiss="modal" style="margin-bottom:0px;">
            <i class="fa fa-ban"></i> Hủy
        </button>
        <button class="btn btn-success" type="submit">
            <i class="fa fa-save"></i> Thêm
        </button>
    </div>
}

NhuDangCenter/Views/HRM_USER/Index.cshtml
@using NhuDangCenter.Models
@model IEnumerable<NhuDangCenter.Models.HRM_USER>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    NhuDangCenterEntities db = new NhuDangCenterEntities();
}

@section huongdan{
    <text>Danh sách tài khoản được sử dụng chương trình</text>
}

<p>
    <a href="@Url.Action("Create", "HRM_USER")" class="btn btn-primary" data-modal><i class="fa fa-plus m-right-xs"></i>Thêm mới</a>
</p>
<table class="table table-bordered table-striped table-hover" id="bangUser">
    <thead>
        <tr>
            <th>STT</th>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>  
            <th>Vai trò</th>          
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td></td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FullName)
                </td> 
                <td>
                    @foreach(HRM_USERROLES ur in item.HRM_USERROLES)
                    {
                        HRM_ROLE r = ur.HRM_ROLE;
                        <text>@r.RoleFullName</text>
                        <br/>
                    }
                </td>               
                <td>
                    <a href="@Url.Action("ChangePassword", "HRM_USER", new { id=item.UserID })" class="btn btn-warning btn-xs" data-modal><i class="fa fa-refresh"></i></a>
                    <a href="@Url.Action("EditUserRoles", "HRM_USER", new { id=item.UserID })" class="btn btn-success btn-xs" data-modal><i class="fa fa-edit"></i></a>
                    <a href="@Url.Action("Delete", "HRM_USER", new { id=item.UserID })" class="btn btn-danger btn-xs" data-modal><i class="fa fa-trash"></i></a>                    
                </td>
            </tr>
        }
    </tbody>
</table>
@section Styles{
    @Styles.Render("~/vendors/DataTables/css")
    @Styles.Render("~/vendors/DataTables/Buttons/css")
}
@section scripts{
    @Scripts.Render("~/vendors/DataTables/js")
    @Scripts.Render("~/vendors/DataTables/Buttons/js")
    @Scripts.Render("~/bundles/jqueryval")
    <!--modal form-->
    @Scripts.Render("~/bundles/modalform")
    <script type="text/javascript">
        $(document).ready(function () {
            LoadDatatable();
        })
        function LoadDatatable() {
            t = $('#bangUser').DataTable({
                "language": {
                    "url": "/vendors/DataTables/langs/Vietnamese.json"
                }
            });
            t.on('order.dt search.dt', function () {
                t.column(0, { search: 'applied', order: 'applied' }).nodes().each(function (cell, i) {
                    cell.innerHTML = i + 1;
                });
            }).draw()
        }
    </script>
}