NhuDangCenter/Models/Lop.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhuDangCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lop()
        {
            this.ChamCongs = new HashSet<ChamCong>();
            this.CTHocViens = new HashSet<CTHocVien>();
            this.LuongGiaoViens = new HashSet<LuongGiaoVien>();
        }
    
        public int Lop_ID { get; set; }
        public string MaLop { get; set; }
        public string Lop_Name { get; set; }
        public Nullable<int> Thu_ID { get; set; }
        public Nullable<int> Ca_ID { get; set; }
        public Nullable<int> CapDo_ID { get; set; }
        public Nullable<System.DateTime> BatDau { get; set; }
        public Nullable<System.DateTime> KetThuc { get; set; }
        public string ThoiGianLop { get; set; }
        public Nullable<int> HocPhi { get; set; }
        public Nullable<int> GiaoVien_ID { get; set; }
        public Nullable<int> TroGiang_ID { get; set; }
        public Nullable<int> Phong_ID { get; set; }
        public Nullable<int> TinhTrangLop_ID { get; set; }
        public Nullable<int> LuongGiangChinh { get; set; }
        public Nullable<int> LuongTroGiang { get; set; }
    
        public virtual Ca Ca { get; set; }
        public virtual CapDo CapDo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChamCong> ChamCongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHocVien> CTHocViens { get; set; }
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual GiaoVien GiaoVien1 { get; set; }
        public virtual Phong Phong { get; set; }
        public virtual Thu Thu { get; set; }
        public virtual TinhTrangLop TinhTrangLop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LuongGiaoVien> LuongGiaoViens { get; set; }
    }
}

NhuDangCenter/Controllers/LopController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NhuDangCenter.Models;

namespace NhuDangCenter.Controllers
{
    public class LopController : Controller
    {
        private NhuDangCenterEntities db = new NhuDangCenterEntities();

        // GET: Lops
        public ActionResult Index()
        {
            var lops = db.Lops.Include(l => l.Ca).Include(l => l.CapDo).Include(l => l.GiaoVien).Include(l => l.Phong).Include(l => l.Thu).Include(l => l.TinhTrangLop);
                 
            return View(lops.ToList());
        }
        // GET: Lops
        public ActionResult ThoiKhoaBieu()
        {
            //Lấy danh sách thứ
            List<Thu> thuList = db.Thus.ToList();
            ViewBag.Thus = thuList;
            var lops = db.store_ThoiKhoaBieu();// db.Lops.Include(l => l.Ca).Include(l => l.CapDo).Include(l => l.GiaoVien).Include(l => l.Phong).Include(l => l.Thu).Include(l => l.TinhTrangLop);

            return View(lops.ToList());
        }
        // GET: Lops
        public ActionResult ThoiKhoaBieu_khoi()
        {
            //Lấy danh sách thứ
            List<string> thuList = new List<string>();
            thuList.Add("2");
            thuList.Add("3");
            thuList.Add("4");
            thuList.Add("5");
            thuList.Add("6");
            thuList.Add("7");
            

            ViewBag.Thus = thuList;
            List<Phong> phongList = db.Phongs.ToList();
            ViewBag.Phongs = phongList.OrderBy(p=>p.Phong_Name);
            List<Ca> caList = db.Cas.ToList();
            ViewBag.Cas = caList;
            var lops = db.store_ThoiKhoaBieu();// db.Lops.Include(l => l.Ca).Include(l => l.CapDo).Include(l => l.GiaoVien).Include(l => l.Phong).Include(l => l.Thu).Include(l => l.TinhTrangLop);

            return View(lops.ToList());
        }
        public ActionResult Index1()
        {
            var lops = db.Lops.Include(l => l.Ca).Include(l => l.CapDo).Include(l => l.GiaoVien).Include(l => l.Phong).Include(l => l.Thu).Include(l => l.TinhTrangLop);

            return View(lops.ToList());
        }
        //set cache để nó load lại cái mới cập nhật
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult LopDuKien()
        {
            var lops = db.Lops.Include(l => l.Ca).Include(l => l.CapDo).Include(l => l.GiaoVien).Include(l => l.Phong).Include(l => l.Thu).Include(l => l.TinhTrangLop)
                .Where(l=>l.BatDau > DateTime.Now) ;
            return PartialView("_LopPartial", lops.ToList());
        }
        public ActionResult LopDangMo()
        {
            var lops = db.Lops.Include(l => l.Ca).Include(l => l.CapDo).Include(l => l.GiaoVien).Include(l => l.Phong).Include(l => l.Thu).Include(l => l.TinhTrangLop)
                .Where(l => l.KetThuc > DateTime.Now && l.BatDau <= DateTime.Now);
            return PartialView("_LopPartial", lops.ToList());
        }
        public ActionResult LopKetThuc()
        {
            var lops = db.Lops.Include(l => l.Ca).Include(l => l.CapDo).Include(l => l.GiaoVien).Include(l => l.Phong).Include(l => l.Thu).Include(l => l.TinhTrangLop)
                .Where(l => l.KetThuc < DateTime.Now);
            return PartialView("_LopPartial", lops.ToList());
        }
        public ActionResult dsLop()
        {
           
            var lops = db.Lops.Include(l => l.Ca).Include(l => l.CapDo).Include(l => l.GiaoVien).Include(l => l.Phong).Include(l => l.Thu).Include(l => l.TinhTrangLop);

            return PartialView(lops.ToList());
        }
       
        public ActionResult dsDiemHocVien(int LopID)
        {
            var cTHocViens = db.CTHocViens.Include(c => c.HocVien).Where(c => c.Lop_ID == LopID);
           // var cTHocViens = db.CTHocViens.Include(c => c.HocVien).Include(c => c.Lop);
            return PartialView(cTHocViens.ToList());
        }
        //Danh sách không thuộc lớp
        public ActionResult dsHocVien0(int LopID)
        {
            //lấy ra danh sách học viên không thuộc lớp đang chọn
            ViewBag.TenLop = db.Lops.Where(l=>l.Lop_ID==LopID).Select(l=>l.Lop_Name).First();
            return PartialView(db.store_Lop_HocVien(LopID).ToList());
             
        }
        //Danh sách trong lớp
        public ActionResult dsHocVien1(int LopID)
        {
            //lấy ra danh sách học viên không thuộc lớp đang chọn
            ViewBag.TenLop = db.Lops.Where(l => l.Lop_ID == LopID).Select(l => l.Lop_Name).First();
            return PartialView(db.store_Lop_HocVien1(LopID).ToList());

        }

        public ActionResult InsertHV(int HocVienID, int LopID)
        {
            db.InsertHocVien_Lop(HocVienID,LopID);
            db.SaveChanges();
            //lấy lại dữ liệu
            return PartialView("dsDiemHocVien", db.CTHocViens.Include(c => c.HocVien).Where(c => c.Lop_ID==LopID));
        }
        //Chuyển học viên từ lớp cũ sang lớp mới
        public ActionResult ChuyenHV(int HocVienID, int LopcuID, int LopmoiID)
        {
            db.store_chuyenHocVien_Lop(LopcuID,LopmoiID,HocVienID);
            db.SaveChanges();
            //lấy lại dữ liệu
            return PartialView("dsDiemHocVien", db.CTHocViens.Include(c => c.HocVien).Where(c => c.Lop_ID == LopcuID));
        }

        public ActionResult dieuKienLoc(int LopID, int HocVienID)
        {
       
            //lấy ra danh sách lớp
            var tv = db.Lops.Where(x => x.Lop_ID != LopID).ToList();
            if (tv == null)
            {
                ViewBag.SelectedPos = -1;
            }
            else
            {
                ViewBag.SelectedPos = LopID;
            }
            return PartialView(tv);
        }
        // GET: Lops/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lop lop = db.Lops.Find(id);
            if (lop == null)
            {
                return HttpNotFound();
            }
            return PartialView(lop);
        }

        // GET: Lops/Details/5
        public ActionResult DetailsLop_HocVien()
        {

            var lops = db.Lops.Include(l => l.Ca).Include(l => l.CapDo).Include(l => l.GiaoVien).Include(l => l.Phong).Include(l => l.Thu).Include(l => l.TinhTrangLop);

            return View(lops.ToList());
        }

       
        // GET: Lops/Create
        public ActionResult Create()
        {
            ViewBag.Ca_ID = new SelectList(db.Cas, "Ca_ID", "Ca_Name");
            ViewBag.CapDo_ID = new SelectList(db.CapDoes, "CapDo_ID", "CapDo_Name");
            ViewBag.GiaoVien_ID = new SelectList(db.GiaoViens, "GiaoVien_ID", "GiaoVien_Name");

            //TRợ giảng có thể không có
            List<SelectListItem> list = new List<SelectListItem>();
            var newItem = new SelectListItem { Text = "(Không chọn)", Value = "" };
            list.Add(newItem);
            var query = (from k in db.GiaoViens                         
                         select new SelectListItem { Text = k.GiaoVien_Name, Value = k.GiaoVien_ID.ToString() }).Distinct();
            list.AddRange(query.ToList());
            ViewBag.TroGiang_ID = list;

            ViewBag.Phong_ID = new SelectList(db.Phongs, "Phong_ID", "Phong_Name");
            ViewBag.Thu_ID = new SelectList(db.Thus, "Thu_ID", "Thu_Name");
            ViewBag.TinhTrangLop_ID = new SelectList(db.TinhTrangLops, "TinhTrangLop_ID", "TinhTrangLop_Name");
            return PartialView();
        }

        // POST: Lops/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Lop_ID,MaLop,Lop_Name,Thu_ID,Ca_ID,CapDo_ID,BatDau,KetThuc,ThoiGianLop,HocPhi,GiaoVien_ID,TroGiang_ID,Phong_ID,TinhTrangLop_ID,LuongTroGiang, LuongGiangChinh")] Lop lop)
        {
            if (ModelState.IsValid)
            {
                db.Lops.Add(lop);
                db.SaveChanges();
                //return RedirectToAction("Index");
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
                //return RedirectToAction("Index", "Lop");
                //return Json(new { result = "Redirect", url = Url.Action("Index", "Lop") });
            }

            ViewBag.Ca_ID = new SelectList(db.Cas, "Ca_ID", "Ca_Name", lop.Ca_ID);
            ViewBag.CapDo_ID = new SelectList(db.CapDoes, "CapDo_ID", "CapDo_Name", lop.CapDo_ID);
            ViewBag.TroGiang_ID = new SelectList(db.GiaoViens, "GiaoVien_ID", "GiaoVien_Name");
            ViewBag.GiaoVien_ID = new SelectList(db.GiaoViens, "GiaoVien_ID", "GiaoVien_Name", lop.GiaoVien_ID);
            ViewBag.Phong_ID = new SelectList(db.Phongs, "Phong_ID", "Phong_Name", lop.Phong_ID);
            ViewBag.Thu_ID = new SelectList(db.Thus, "Thu_ID", "Thu_Name", lop.Thu_ID);
            ViewBag.TinhTrangLop_ID = new SelectList(db.TinhTrangLops, "TinhTrangLop_ID", "TinhTrangLop_Name", lop.TinhTrangLop_ID);
            return PartialView(lop);
        }

        // GET: Lops/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lop lop = db.Lops.Find(id);
            if (lop == null)
            {
                return HttpNotFound();
            }
            ViewBag.Ca_ID = new SelectList(db.Cas, "Ca_ID", "Ca_Name", lop.Ca_ID);
            ViewBag.CapDo_ID = new SelectList(db.CapDoes, "CapDo_ID", "CapDo_Name", lop.CapDo_ID);

            //TRợ giảng có thể không có

NhuDangCenter/Views/Lop/Delete.cshtml
@model NhuDangCenter.Models.Lop

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Bạn có chắc muốn xóa lớp học này?</h4>
</div>
<div class="modal-body">
    <table class="table no-border table-striped table-hover">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MaLop)
            </th>

            <td>
                @Html.DisplayFor(model => model.MaLop)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Lop_Name)
            </th>

            <td>
                @Html.DisplayFor(model => model.Lop_Name)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BatDau)
            </th>

            <td>
                @Html.DisplayFor(model => model.BatDau)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.KetThuc)
            </th>

            <td>
                @Html.DisplayFor(model => model.KetThuc)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ThoiGianLop)
            </th>

            <td>
                @Html.DisplayFor(model => model.ThoiGianLop)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.HocPhi)
            </th>

            <td>
                @Html.DisplayFor(model => model.HocPhi)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TroGiang_ID)
            </th>

            <td>
                @Html.DisplayFor(model => model.TroGiang_ID)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TroGiang_ID)
            </th>

            <td>
                @Html.DisplayFor(model => model.Ca.Ca_Name)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CapDo_ID)
            </th>

            <td>
                @Html.DisplayFor(model => model.CapDo.CapDo_Name)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GiaoVien_ID)
            </th>

            <td>
                @Html.DisplayFor(model => model.GiaoVien.GiaoVien_Name)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Phong_ID)
            </th>

            <td>
                @Html.DisplayFor(model => model.Phong.Phong_Name)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Thu_ID)
            </th>

            <td>
                @Html.DisplayFor(model => model.Thu.Thu_Name)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LuongGiangChinh)
            </th>

            <td>
                @Html.DisplayFor(model => model.LuongGiangChinh)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LuongTroGiang)
            </th>

            <td>
                @Html.DisplayFor(model => model.LuongTroGiang)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TinhTrangLop_ID)
            </th>

            <td>
                @Html.DisplayFor(model => model.TinhTrangLop.TinhTrangLop_Name)
            </td>

        </tr>

    </table>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="modal-footer">
        <button class="btn btn-default" data-dismiss="modal" style="margin-bottom:0px;">
            <i class="fa fa-ban"></i> Hủy
        </button>
        <button class="btn btn-danger" type="submit">
            <i class="fa fa-trash"></i>Xóa
        </button>
    </div>
}

NhuDangCenter/Views/Lop/Index.cshtml
@model IEnumerable<NhuDangCenter.Models.Lop>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section huongdan{
    <text>DANH SÁCH LỚP</text>
}




<p>
    <a data-modal href="@Url.Action("Create", "Lop")" class="btn btn-primary"><i class="fa fa-plus m-right-xs"></i>Thêm mới</a>
</p>

@*<div class="col-md-9 col-sm-9 col-xs-12">
    <div class="" role="tabpanel" data-example-id="togglable-tabs">
        <ul id="myTabs" class="nav nav-tabs bar_tabs" role="tablist">
            <li role="presentation" class="active">
                <a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true" title="Thông tin cơ bản">Tất cả các lớp</a>
            </li>
            <li role="presentation" class="">
                <a href="#tab_content2" role="tab" id="profile-tab2" data-toggle="tab" aria-expanded="false" data-url="@Url.Action("LopDuKien", "Lop")" title="Lớp dự kiến">Lớp dự kiến</a>
            </li>
            <li role="presentation" class="">
                <a href="#tab_content3" role="tab" id="profile-tab3" data-toggle="tab" aria-expanded="false" data-url="@Url.Action("LopDangMo", "Lop")" title="Lớp đang mở">Lớp đang mở</a>
            </li>
            <li role="presentation" class="">
                <a href="#tab_content4" role="tab" id="profile-tab4" data-toggle="tab" aria-expanded="false" data-url="@Url.Action("LopKetThuc", "Lop")" title="Lớp kết thúc">Lớp kết thúc</a>
            </li>
        </ul>
        <div id="myTabContent" class="tab-content">
            <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">*@
                <table id="LopList" class="table table-striped jambo_table border-right action-table">
                    <thead>
                        <tr>
                            <th></th>
                            @*<th>
                                @Html.DisplayNameFor(model => model.MaLop)
                            </th>*@
                            <th>
                                @Html.DisplayNameFor(model => model.Lop_Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.BatDau)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.KetThuc)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ThoiGianLop)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.HocPhi)
                            </th>
                            @*<th>
                                @Html.DisplayNameFor(model => model.TroGiang_ID)
                            </th>*@
                            @*<th>
                                @Html.DisplayNameFor(model => model.Ca_ID)
                            </th>*@
                            @*<th>
                                @Html.DisplayNameFor(model => model.CapDo_ID)
                            </th>*@
                            <th>
                                @Html.DisplayNameFor(model => model.GiaoVien_ID)
                            </th>
                            @*<th>
                                @Html.DisplayNameFor(model => model.Phong_ID)
                            </th>*@
                            @*<th>
                                @Html.DisplayNameFor(model => model.Thu_ID)
                            </th>*@
                            @*<th>
                                @Html.DisplayNameFor(model => model.LuongTroGiang)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.LuongGiangChinh)
                            </th>*@
                            <th>
                                @Html.DisplayNameFor(model => model.TinhTrangLop_ID)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @{ int stt = 1;}
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td style="text-align:center">@stt</td>
                                @*<td>
                                    @Html.DisplayFor(modelItem => item.MaLop)
                                </td>*@
                                <td style="width:300px; text-align:left">
                                    <a href="@Url.Action("Details", "Lop", new { id=item.Lop_ID })" data-modal>@item.Lop_Name</a>
                                    @*@Html.DisplayFor(modelItem => item.Lop_Name)*@
                                </td>
                                <td style="text-align:center">
                                    @Html.DisplayFor(modelItem => item.BatDau)
                                </td>
                                <td style="text-align:center">
                                    @Html.DisplayFor(modelItem => item.KetThuc)
                                </td>
                                <td style="width:30px; text-align:center">
                                    @Html.DisplayFor(modelItem => item.ThoiGianLop)
                                </td>
                                <td style="text-align:right">
                                    @Html.DisplayFor(modelItem => item.HocPhi)
                                </td>
                                @*<td>
                                    @Html.DisplayFor(modelItem => item.TroGiang_ID)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Ca.Ca_Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CapDo.CapDo_Name)
                                </td>*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.GiaoVien.GiaoVien_Name)
                                </td>
                                @*<td>
                                    @Html.DisplayFor(modelItem => item.Phong.Phong_Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Thu.Thu_Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LuongTroGiang)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LuongGiangChinh)
                                </td>*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.TinhTrangLop.TinhTrangLop_Name)
                                </td>
                                <td>
                                    <a href="@Url.Action("Edit", "Lop", new { id=item.Lop_ID })" class="btn btn-success btn-xs" data-modal><i class="fa fa-edit"></i></a>
                                    <a href="@Url.Action("Delete", "Lop", new { id=item.Lop_ID })" class="btn btn-danger btn-xs" data-modal><i class="fa fa-trash"></i></a>

                                </td>
                                @{ stt++;}
                            </tr>

                                    }
                    </tbody>

                </table>
            @*</div>
            <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">
                <!-- bang danh sach qua trinh cong tac -->
                <!-- end user projects -->
            </div>
            <div role="tabpanel" class="tab-pane fade" id="tab_content3" aria-labelledby="profile-tab">

            </div>

            <div role="tabpanel" class="tab-pane fade" id="tab_content4" aria-labelledby="profile-tab">

            </div>
            
            </div>
        </div>
    </div>*@
@section Styles{
    @Styles.Render("~/vendors/DataTables/css")
    @Styles.Render("~/vendors/DataTables/Buttons/css")
}
@section scripts{
    @Scripts.Render("~/vendors/DataTables/js")
    @Scripts.Render("~/vendors/DataTables/Buttons/js")
    @Scripts.Render("~/bundles/jqueryval")
    <!--modal form-->
    @Scripts.Render("~/bundles/modalform")
    <script type="text/javascript">
        $(document).ready(function () {
            var t = $('#LopList').DataTable({
                "language": {
                    "url": "/vendors/DataTables/langs/Vietnamese.json"
                },
                "columnDefs": [{
                    "searchable": false,
                    "orderable": false,
                    "targets": 0
                },
                {
                    "searchable": false,
                    "orderable": false,
                    "targets":3
                },
                ],
                "order": [[0, 'asc']]
            });
            t.on('order.dt search.dt', function () {
                t.column(0, { search: 'applied', order: 'applied' }).nodes().each(function (cell, i) {
                    cell.innerHTML = i + 1;
                });
            }).draw();
        });
        
    </script>
}

NhuDangCenter/Views/Lop/dsDiemHocVien.cshtml
@model IEnumerable<NhuDangCenter.Models.CTHocVien>

 
<table id="tblCTHocVien" class="table table-striped jambo_table border-right action-table">
    <thead>
        
                <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.HocVien.HocVien_Name)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.Diem1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Diem2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Diem3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Diem4)
            </th>
            
            <td></td>
            
        </tr>
    </thead>
    <tbody>
        @{ int stt = 1;}
        @foreach (var item in Model)
        {
            <tr>
                <td>@stt</td>
                <td>
                    @Html.DisplayFor(modelItem => item.HocVien.HocVien_Name)
                </td>
                
                <td>
                    @Html.DisplayFor(modelItem => item.Diem1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Diem2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Diem3)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Diem4)
                </td>
                <td>
                 
                    <a href="#" onclick="KiemTraBangCap(@item.CTHocVien_ID);"><i class="fa fa-check"></i></a>
                 </td>
                 
                @{ stt++;}
            </tr>
                    }
    </tbody>
</table>
 

NhuDangCenter/Views/Lop/dsHocVien0.cshtml
@model  IEnumerable<NhuDangCenter.Models.store_Lop_HocVien_Result>

 Không thuộc lớp @ViewBag.TenLop
<table id="tblHocVien" class="table table-bordered table-hover table-striped">
    <thead>
        
    <tr>
            <th></th>
            <th>
                Họ tên
            </th>
            <th>
               Ngày sinh
            </th>
             
            
        </tr>
    </thead>
    <tfoot>

        <tr>
            <th></th>
            <th>
                Họ tên
            </th>
            <th>
                Ngày sinh
            </th>


        </tr>
    </tfoot>
    <tbody>
        
        @foreach (var item in Model)
        {
            string rowID = item.HocVien_ID.ToString();
         
            <tr id="@rowID">
                <td></td>
                <td>
                    @Html.DisplayFor(modelItem => item.HocVien_Name)
                </td>
                <td>
                    @String.Format("{0:dd/MM/yyyy}", item.NgaySinh)
                  @*  @Html.DisplayFor(modelItem => item.NgaySinh)*@
                </td>

            </tr>
                    }
    </tbody>
</table>
 