NhuDangCenter/Controllers/BaoCaoThuChiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NhuDangCenter.Models;
using Microsoft.Office.Interop.Excel;
using System.IO;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System.Drawing;

namespace NhuDangCenter.Controllers
{
    public class BaoCaoThuChiController : Controller
    {
        private NhuDangCenterEntities db = new NhuDangCenterEntities();
        // GET: BaoCaoThuChi
        [Authorize(Roles = "Quan tri")]
        public ActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "Quan tri")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index([Bind(Include = "TuNgay,DenNgay")] TuNgayDenNgay obj)
        {
            if (ModelState.IsValid)
            {
                var result = db.sp_T_BaoCaoThuChi(obj.TuNgay, obj.DenNgay).OrderByDescending(x =>x.PhanLoai).ToList();
                ViewBag.BangKe = result;
                return View(obj);
            }
            return View();
        }
        public FileResult XuatExcel(DateTime tuNgay, DateTime denNgay)
        {
            var duLieu = db.sp_T_BaoCaoThuChi(tuNgay, denNgay).OrderByDescending(x => x.PhanLoai).ToList();

            //đầu tiên là in tiêu đề
            string tieuDe = "Từ ngày " + tuNgay.ToString("dd/MM/yyyy") + " đến ngày " + denNgay.ToString("dd/MM/yyyy");
                     
            FileResult result = null;
            string server = Server.MapPath("~/App_Data");

            DirectoryInfo outputDir = new DirectoryInfo(Environment.GetFolderPath(Environment.SpecialFolder.CommonDocuments));

            FileInfo templateFile = new FileInfo(server + "//thongkethuchi.xltx");
            FileInfo newFile = new FileInfo(outputDir.FullName + @"\thongkethuchi.xlsx");
            if (newFile.Exists)
            {
                newFile.Delete();  // ensures we create a new workbook
                newFile = new FileInfo(outputDir.FullName + @"\thongkethuchi.xlsx");
            }
            using (ExcelPackage package = new ExcelPackage(newFile, templateFile))
            {
                //Sheet xuất dữ liệu
                ExcelWorksheet worksheet = package.Workbook.Worksheets[1];

                //****************************************
                //CODE INSERT THỐNG KÊ THU CHI
                //****************************************
                //Vị trí row sẽ insert:
                //in thống ke
                worksheet.Cells[2, 1].Value = tieuDe;
                worksheet.Cells[2, 1].Style.HorizontalAlignment = OfficeOpenXml.Style.ExcelHorizontalAlignment.Center;
                worksheet.Cells[2, 1].Style.VerticalAlignment = ExcelVerticalAlignment.Center;

                int row = 4;
                int stt = 1;
                foreach (sp_T_BaoCaoThuChi_Result item in duLieu)
                {
                    worksheet.Cells[row, 1].Value = stt;                    
                    worksheet.Cells[row, 1].Style.HorizontalAlignment = OfficeOpenXml.Style.ExcelHorizontalAlignment.Center;
                    worksheet.Cells[row, 1].Style.VerticalAlignment = ExcelVerticalAlignment.Center;

                    worksheet.Cells[row, 2].Value = item.PhanLoai;                    
                    worksheet.Cells[row, 2].Style.HorizontalAlignment = OfficeOpenXml.Style.ExcelHorizontalAlignment.Center;
                    worksheet.Cells[row, 2].Style.VerticalAlignment = ExcelVerticalAlignment.Center;

                    worksheet.Cells[row, 3].Value = item.NoiDung;
                    worksheet.Cells[row, 3].Style.HorizontalAlignment = OfficeOpenXml.Style.ExcelHorizontalAlignment.Left;
                    worksheet.Cells[row, 3].Style.VerticalAlignment = ExcelVerticalAlignment.Center;

                    if (item.ThuHocPhi > 0)
                    {
                        worksheet.Cells[row, 4].Value = item.ThuHocPhi;
                        worksheet.Cells[row, 4].Style.HorizontalAlignment = OfficeOpenXml.Style.ExcelHorizontalAlignment.Right;
                        worksheet.Cells[row, 4].Style.VerticalAlignment = ExcelVerticalAlignment.Center;
                    }
                    else
                    {
                        worksheet.Cells[row, 4].Value = item.ChiKhac;
                        worksheet.Cells[row, 4].Style.HorizontalAlignment = OfficeOpenXml.Style.ExcelHorizontalAlignment.Right;
                        worksheet.Cells[row, 4].Style.VerticalAlignment = ExcelVerticalAlignment.Center;
                    }
                    row++;
                    stt++;
                }

                //Switch the PageLayoutView back to normal
                worksheet.View.PageLayoutView = false;
                // save our new workbook and we are done!
                package.Save();


                string absolutePath = newFile.FullName;// = _environment.WebRootPath + @"\" + relativePath;

                if (System.IO.File.Exists(absolutePath))
                {
                    string fileName = System.IO.Path.GetFileName(absolutePath);
                    byte[] fileBytes = System.IO.File.ReadAllBytes(absolutePath);
                    result = File(fileBytes, "application/x-msdownload", fileName);
                }
                return result;
            }

        }
    }
}

NhuDangCenter/Views/BaoCaoThuChi/Index.cshtml
@model NhuDangCenter.Models.TuNgayDenNgay
@{
    IEnumerable<NhuDangCenter.Models.sp_T_BaoCaoThuChi_Result> bangKe = (IEnumerable<NhuDangCenter.Models.sp_T_BaoCaoThuChi_Result>)ViewBag.BangKe;
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-inline">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row" style="text-align:center; margin-bottom:15px;">
            <div class="form-group">
                    @Html.LabelFor(model => model.TuNgay, htmlAttributes: new { @class = "control-label" })
             
                    @Html.EditorFor(model => model.TuNgay, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TuNgay, "", new { @class = "text-danger" })

            </div>
            <div class="form-group">
                    @Html.LabelFor(model => model.DenNgay, htmlAttributes: new { @class = "control-label" })
                
                    @Html.EditorFor(model => model.DenNgay, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DenNgay, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <div>
                    <button class="btn btn-success" type="submit">
                        <i class="fa fa-calculator"></i> Xem thông tin
                    </button>
                </div>
            </div>
        </div>

        
    </div>
}
@if (bangKe != null)
{
    <p>
        <a href="@Url.Action("XuatExcel", "BaoCaoThuChi", new { tuNgay = Model.TuNgay, denNgay = Model.DenNgay })" class="btn btn-primary"><i class="fa fa-file-excel-o m-right-xs"></i>Xuất excel báo cáo</a>
    </p>
    <table class="table table-bordered table-striped table-hover" id="bangKe">
        <thead>
            <tr>
                <th>STT</th>
                <th>
                    Nội dung
                </th>
                <th>
                    Thu
                </th>
                <th>
                    Chi
                </th>
                <th>
                    Phân loại
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in bangKe)
            {
                <tr>
                    <td></td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NoiDung)
                    </td>
                    <td>
                        @if (item.ThuHocPhi > 0)
                        {
                            @Html.DisplayFor(modelItem => item.ThuHocPhi)
                        }                        
                    </td>
                    <td>
                        @if (item.ChiKhac > 0)
                        {
                            @Html.DisplayFor(modelItem => item.ChiKhac)
                        }
                        
                    </td>                    
                    <td>
                        @Html.DisplayFor(modelItem => item.PhanLoai)
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
@section Styles{
    @Styles.Render("~/vendors/DataTables/css")
    @Styles.Render("~/vendors/DataTables/Buttons/css")
}
@section scripts{
    @Scripts.Render("~/vendors/DataTables/js")
    @Scripts.Render("~/vendors/DataTables/Buttons/js")
    @Scripts.Render("~/bundles/jqueryval")
    <!--modal form-->
    @Scripts.Render("~/bundles/modalform")
    <script type="text/javascript">
        var columnGroup = 4;
        $(document).ready(function () {
            LoadDatatable();
        })
        function LoadDatatable() {
            t = $('#bangKe').DataTable({
                "language": {
                    "url": "/vendors/DataTables/langs/Vietnamese.json"
                },
                "columnDefs": [
                    { "visible": false, "targets": columnGroup }
                ],
                "order": [[columnGroup, 'asc']],
                "displayLength": 25,
                "drawCallback": function (settings) {
                    var api = this.api();
                    var rows = api.rows({ page: 'current' }).nodes();
                    var last = null;

                    api.column(columnGroup, { page: 'current' }).data().each(function (group, i) {
                        if (last !== group) {
                            $(rows).eq(i).before(
                                '<tr class="group" style="background-color:#fff;"><td colspan="5"><strong>' + group + '</strong></td></tr>'
                            );

                            last = group;
                        }
                    });
                }
            });
            t.on('order.dt search.dt', function () {
                t.column(0, { search: 'applied', order: 'applied' }).nodes().each(function (cell, i) {
                    cell.innerHTML = i + 1;
                });
            }).draw()
        }
    </script>
}