NhuDangCenter/Models/ChuongTrinh.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhuDangCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuongTrinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChuongTrinh()
        {
            this.CapDoes = new HashSet<CapDo>();
        }
    
        public int ChuongTrinh_ID { get; set; }
        public string ChuongTrinh_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CapDo> CapDoes { get; set; }
    }
}

NhuDangCenter/Controllers/Thanh/ChuongTrinhController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NhuDangCenter.Models;

namespace NhuDangCenter.Controllers.Thanh
{
    public class ChuongTrinhController : Controller
    {
        private NhuDangCenterEntities db = new NhuDangCenterEntities();

        // GET: ChuongTrinh
        public ActionResult Index()
        {
            return View(db.ChuongTrinhs.ToList());
        }

        // GET: ChuongTrinh/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChuongTrinh chuongTrinh = db.ChuongTrinhs.Find(id);
            if (chuongTrinh == null)
            {
                return HttpNotFound();
            }
            return View(chuongTrinh);
        }

        // GET: ChuongTrinh/Create
        public ActionResult Create()
        {
            return PartialView();
        }

        // POST: ChuongTrinh/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ChuongTrinh_ID,ChuongTrinh_Name")] ChuongTrinh chuongTrinh)
        {
            if (ModelState.IsValid)
            {
                db.ChuongTrinhs.Add(chuongTrinh);
                db.SaveChanges();
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }

            return PartialView(chuongTrinh);
        }

        // GET: ChuongTrinh/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChuongTrinh chuongTrinh = db.ChuongTrinhs.Find(id);
            if (chuongTrinh == null)
            {
                return HttpNotFound();
            }
            return PartialView(chuongTrinh);
        }

        // POST: ChuongTrinh/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ChuongTrinh_ID,ChuongTrinh_Name")] ChuongTrinh chuongTrinh)
        {
            if (ModelState.IsValid)
            {
                db.Entry(chuongTrinh).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            return PartialView(chuongTrinh);
        }

        // GET: ChuongTrinh/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChuongTrinh chuongTrinh = db.ChuongTrinhs.Find(id);
            if (chuongTrinh == null)
            {
                return HttpNotFound();
            }
            return PartialView(chuongTrinh);
        }

        // POST: ChuongTrinh/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ChuongTrinh chuongTrinh = db.ChuongTrinhs.Find(id);
            db.ChuongTrinhs.Remove(chuongTrinh);
            db.SaveChanges();
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NhuDangCenter/Views/ChuongTrinh/Create.cshtml
@model NhuDangCenter.Models.ChuongTrinh
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Thêm chương trình học</h4>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="modal-body">
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.ChuongTrinh_Name, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.ChuongTrinh_Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ChuongTrinh_Name, "", new { @class = "text-danger" })
                </div>
            </div>
            
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn btn-default" data-dismiss="modal" style="margin-bottom:0px;">
            <i class="fa fa-ban"></i> Hủy
        </button>
        <button class="btn btn-success" type="submit">
            <i class="fa fa-save"></i> Lưu thông tin
        </button>
    </div>

}

NhuDangCenter/Views/ChuongTrinh/Delete.cshtml
@model NhuDangCenter.Models.ChuongTrinh

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Bạn có chắc muốn xóa chương trình này?</h4>
</div>
<div class="modal-body">
    <table class="table no-border table-striped table-hover">
        <tr>
            <th>@Html.DisplayNameFor(model => model.ChuongTrinh_Name):</th>
            <td>@Html.DisplayFor(model => model.ChuongTrinh_Name)</td>
        </tr>
                    
    </table>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="modal-footer">
        <button class="btn btn-default" data-dismiss="modal" style="margin-bottom:0px;">
            <i class="fa fa-ban"></i> Hủy
        </button>
        <button class="btn btn-danger" type="submit">
            <i class="fa fa-trash"></i>Xóa
        </button>
    </div>
}

NhuDangCenter/Views/ChuongTrinh/Edit.cshtml
@model NhuDangCenter.Models.ChuongTrinh
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Sửa chương trình học</h4>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="modal-body">
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model =>model.ChuongTrinh_ID)
            <div class="form-group">
                @Html.LabelFor(model => model.ChuongTrinh_Name, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.ChuongTrinh_Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ChuongTrinh_Name, "", new { @class = "text-danger" })
                </div>
            </div>
          
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn btn-default" data-dismiss="modal" style="margin-bottom:0px;">
            <i class="fa fa-ban"></i> Hủy
        </button>
        <button class="btn btn-success" type="submit">
            <i class="fa fa-save"></i> Lưu thông tin
        </button>
    </div>

}

NhuDangCenter/Views/ChuongTrinh/Index.cshtml
@model IEnumerable<NhuDangCenter.Models.ChuongTrinh>

@{
    ViewBag.Title = "Chương trình học";
}
@section huongdan{
    <text>Danh sách các chương trình học</text>
}
<p>
    <a href="@Url.Action("Create", "ChuongTrinh")" class="btn btn-primary" data-modal><i class="fa fa-plus m-right-xs"></i>Thêm mới</a>
</p>
<table class="table table-bordered table-striped table-hover" id="bangCa">
        <thead>
            <tr>
                <th>STT</th>
                <th>
                   Tên chương trình
                </th>                               
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td></td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ChuongTrinh_Name)
                    </td>                                       
                    <td>
                        <a href="@Url.Action("Edit", "ChuongTrinh", new { id=item.ChuongTrinh_ID })" class="btn btn-success btn-xs" data-modal><i class="fa fa-edit"></i></a>
                        <a href="@Url.Action("Delete", "ChuongTrinh", new { id=item.ChuongTrinh_ID })" class="btn btn-danger btn-xs" data-modal><i class="fa fa-trash"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

@section Styles{
    @Styles.Render("~/vendors/DataTables/css")
    @Styles.Render("~/vendors/DataTables/Buttons/css")
}
@section scripts{
    @Scripts.Render("~/vendors/DataTables/js")
    @Scripts.Render("~/vendors/DataTables/Buttons/js")
    @Scripts.Render("~/bundles/jqueryval")
    <!--modal form-->
    @Scripts.Render("~/bundles/modalform")
    <script type="text/javascript">
        $(document).ready(function () {
            LoadDatatable();
        })
        function LoadDatatable() {
            t = $('#bangCa').DataTable({
                "language": {
                    "url": "/vendors/DataTables/langs/Vietnamese.json"
                }
            });
            t.on('order.dt search.dt', function () {
                t.column(0, { search: 'applied', order: 'applied' }).nodes().each(function (cell, i) {
                    cell.innerHTML = i + 1;
                });
            }).draw()
        }
    </script>
}